name: build
on: 
  push:
    branches:
      - 'current'
jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Java 17
      uses: actions/setup-java@v1
      with:
        java-version: 17
        server-id: ossrh
        server-username: MAVEN_USERNAME
        server-password: MAVEN_PASSWORD
    - name: Build project
      run: mvn -B -ntp install
    - name: Deploy Linux .tar.gz file
      run: |
        cd cli-linux
        mvn -B -ntp deploy
      env:
        MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
        MAVEN_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
