name: build
on: 
  push:
    branches:
      - 'master'
jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Java 16
      uses: actions/setup-java@v1
      with:
        java-version: 16
        server-id: ossrh
        server-username: MAVEN_USERNAME
        server-password: MAVEN_PASSWORD
    - name: Build project
      run: mvn -B -ntp install
    - name: Create Linux .tar.gz file
      run: mvn -B -ntp -P linux install
    - name: Deploy Linux .tar.gz file
      run: |
        cd cli-linux
        mvn -B -ntp deploy
      env:
        MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
        MAVEN_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
  macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Java 16
      uses: actions/setup-java@v1
      with:
        java-version: 16
        server-id: ossrh
        server-username: MAVEN_USERNAME
        server-password: MAVEN_PASSWORD
    - name: Build project
      run: mvn -B -ntp install
    - name: Create macOS .dmg file
      run: mvn -B -ntp -P macos install
    - name: Deploy macOS .dmg file
      run: |
        cd cli-macos
        mvn -B -ntp deploy
      env:
        MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
        MAVEN_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
  windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Java 16
      uses: actions/setup-java@v1
      with:
        java-version: 16
        server-id: ossrh
        server-username: MAVEN_USERNAME
        server-password: MAVEN_PASSWORD
    - name: Build project
      run: mvn -B -ntp install
    - name: Create Windows .msi file
      run: mvn -B -ntp -P windows install
    - name: Deploy Windows .msi file
      run: |
        cd cli-windows
        mvn -B -ntp deploy
      env:
        MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
        MAVEN_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
