name: build
on: 
  push:
    branches:
      - 'master'
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Java 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Build project
      run: mvn -B -ntp install
    - name: Login to Docker Hub
      uses: azure/docker-login@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}      
    - name: Build amd64 image
      run: |
        cd webapp
        docker build -f Dockerfile.amd64 -t manorrock/ocelot:amd64-latest .
        docker push manorrock/ocelot:amd64-latest
    - name: Build arm32v6 image
      run: |
        cd webapp
        docker build -f Dockerfile.arm32v6 -t manorrock/ocelot:arm32v6-latest .
        docker push manorrock/ocelot:arm32v6-latest
    - name: Push Docker manifest
      run: |
        export DOCKER_CLI_EXPERIMENTAL=enabled
        docker manifest create manorrock/ocelot:latest \
          manorrock/ocelot:amd64-latest \
          manorrock/ocelot:arm32v6-latest
        docker manifest annotate manorrock/ocelot:latest \
          manorrock/ocelot:amd64-latest --os linux --arch amd64
        docker manifest annotate manorrock/ocelot:latest \
          manorrock/ocelot:arm32v6-latest --os linux --arch arm
        docker manifest push manorrock/ocelot:latest
  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Java 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
        server-id: ossrh
        server-username: MAVEN_USERNAME
        server-password: MAVEN_PASSWORD
    - name: Build project
      run: mvn -B -ntp install
    - name: Create Linux .tar.gz file
      run: mvn -B -ntp -P linux install
    - name: Deploy Linux .tar.gz file
      run: |
        cd cli-linux
        mvn -B -ntp deploy
      env:
        MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
        MAVEN_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
  macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Java 16
      uses: actions/setup-java@v1
      with:
        java-version: 16
        server-id: ossrh
        server-username: MAVEN_USERNAME
        server-password: MAVEN_PASSWORD
    - name: Build project
      run: mvn -B -ntp install
    - name: Create macOS .dmg file
      run: mvn -B -ntp -P macos install
    - name: Deploy macOS .dmg file
      run: |
        cd cli-macos
        mvn -B -ntp deploy
      env:
        MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
        MAVEN_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
  windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Java 16
      uses: actions/setup-java@v1
      with:
        java-version: 16
        server-id: ossrh
        server-username: MAVEN_USERNAME
        server-password: MAVEN_PASSWORD
    - name: Build project
      run: mvn -B -ntp install
    - name: Create Windows .msi file
      run: mvn -B -ntp -P windows install
    - name: Deploy Windows .msi file
      run: |
        cd cli-windows
        mvn -B -ntp deploy
      env:
        MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
        MAVEN_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
