name: release
on:
  push:
    tags:        
      - v*
jobs:
  maven:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v1
    - name: Set up Java 17
      uses: actions/setup-java@v1
      with:
        java-version: 17
        server-id: ossrh
        server-username: MAVEN_USERNAME
        server-password: MAVEN_PASSWORD
        gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
        gpg-passphrase: MAVEN_GPG_PASSPHRASE
    - name: Build with Maven
      run: |
        mvn -B -DskipTests=true -DskipITs=true -ntp -P release deploy
      env:
        MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
        MAVEN_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
        MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
    - name: Login to GHCR
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Push to GHCR
      run: |
        cd azure-keyvault
        mvn -B -DskipTests=true -DskipITs=true -ntp docker:build docker:push
        cd ../azure-appconfig
        mvn -B -DskipTests=true -DskipITs=true -ntp docker:build docker:push
